### ISSUE TITLE
Site not responsive on different screens

### ISSUE THREAD

**Issue by saurabh0402** [fossasia/susper.com#84] opened 2017-02-20 21:06 UTC
I was testing out the site on different screen sizes and it seems that the site is not responsive on all screens. Here are the screenshots:
![screenshot_2017-02-21_02-32-46](https://cloud.githubusercontent.com/assets/12875685/23141754/4efd79d0-f7de-11e6-87e8-8da28194f6c1.png)
![screenshot_2017-02-21_02-32-57](https://cloud.githubusercontent.com/assets/12875685/23141756/5291795c-f7de-11e6-8b08-353aed704555.png)
I would like to work on this issue. Thanks

**Comment by harshit98** [comment] 2017-02-20 21:47
@saurabh0402 Right now, we're enhancing the site for better user experience. Even - images section is also being re-factored. So, we should keep the responsive design issue as a low priority right now. What you think @nikhilrayaprolu ?

**Comment by nikhilrayaprolu** [comment] 2017-02-21 10:01
@saurabh0402 if you feel like you could contribute upon this issue . go ahead.There are alot changes that would happen in the near future , but we could start maintaining responsive design on each pull that would change the design aspects of susper.

**Comment by harshit98** [comment] 2017-02-28 03:44
@saurabh0402 any updates regarding this issue?

**Comment by sandeepm96** [comment] 2017-02-28 10:54
I think maintaining a responsive design from the start is essential. So I am willing to contribute on this.

**Comment by harshit98** [comment] 2017-02-28 12:41
Here is one more screenshot regarding to responsiveness - 

![screenshot_20170228-094830](https://cloud.githubusercontent.com/assets/22245418/23405592/f9a781a2-fde0-11e6-81ea-ed07d498dd3c.png)

@sandeepm96 You can go ahead. Don't forget to post screenshots after fix within your PR. :)

**Comment by sandeepm96** [comment] 2017-02-28 15:14
@harshit98 I have started working on it. Using bootstrap components to get it done. I will post screenshots within the PR whenever its ready. :)

**Comment by Marauderer97** [comment] 2017-03-04 05:22
@sandeepm96 Great work! A friendly tip, next time, use keywords like fixes #issue_number or solves issue_number, within your message in your PR, when you are certain the problem is fixed, this will close the issue automatically. Also, always reference your issue, in the PR.

Closing this issue now, since it has been fixed.

**Comment by sandeepm96** [comment] 2017-03-04 05:36
@Marauderer97 Actually this is not completely done. That's why I didn't. Responsiveness has been added to home page. It is still to be done in the other pages.Could you please reopen this issue. :)

**Comment by Marauderer97** [comment] 2017-03-04 06:03
@sandeepm96 My bad, please carry on :smile:

**Comment by Marauderer97** [comment] 2017-03-04 06:04
#98 can be addressed here too.

**Comment by harshit98** [comment] 2017-03-13 20:16
@nikhilrayaprolu Please close this issue as all the pages are now responsive.

**Closed** 2017-03-14 13:07 UTC
Labels: enhancement
